using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.Serialization;

namespace LurkingNinja.Input.Editor
{
    public class InputCodegenSettings : ScriptableObject
    {
        private const string InputCodegenConfigFolder = "Assets/Plugins/LurkingNinja/Editor";
        private const string InputCodegenConfigFile = InputCodegenConfigFolder + "/InputCodegenConfig.asset";

        public bool inputCodegenEnabled = true;

        public string inputNamespace = "LurkingNinja.Input";
        public string path = "Assets/Plugins/LurkingNinja/InputCodegen/";
        [Space(10), TextArea(20, 20)]
        public string template = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated: {0}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine.InputSystem;

namespace {5}
{{
    public struct {1}
    {{
        private InputActionAsset _asset;

        public {1}(InputActionAsset asset)
        {{
            _asset = asset;
{2}
        }}

        public void Enable() => _asset.Enable();
        public void Disable() => _asset.Disable();

{3}{4}
    }}
}}
";
        [Space(10), TextArea(10, 20)]
        public string classTemplate = @"        public struct {0}Actions
        {{
{2}
            public void Enable() => _actionMap.Enable();
            public void Disable() => _actionMap.Disable();

            private InputActionMap _actionMap;

            internal {0}Actions(InputActionAsset asset)
            {{
                _actionMap = asset.FindActionMap(""{1}""); 

{3}
            }}
        }}";

        private static InputCodegenSettings _config;

        public static InputCodegenSettings Get => GenerateConfigFile();
        
        private static InputCodegenSettings GenerateConfigFile()
        {
            if (_config != null) return _config;
            _config = AssetDatabase.LoadAssetAtPath<InputCodegenSettings>(InputCodegenConfigFile);
            if (_config != null) return _config;
            if (!Directory.Exists(InputCodegenConfigFolder))
                Directory.CreateDirectory(InputCodegenConfigFolder);
            _config = CreateInstance<InputCodegenSettings>();
            AssetDatabase.CreateAsset(_config, InputCodegenConfigFile);
            AssetDatabase.SaveAssets();
            return _config;
        }
        
        [MenuItem("Tools/LurkingNinja/Input Codegen Config", false)]
        private static void InputCodegenConfig()
        {
            GenerateConfigFile();
            EditorUtility.FocusProjectWindow();
            EditorGUIUtility.PingObject(_config);
            Selection.activeObject = _config;
        }
    }
}
